name: hid-inspector
options:
  bundleIdPrefix: org.pqrs

targets:
  hid-inspector:
    type: tool
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - '-Wall'
          - '-Werror'
          - '-std=c++23'
    dependencies:
      - sdk: CoreFoundation.framework
      - sdk: IOKit.framework
    settings:
        SYSTEM_HEADER_SEARCH_PATHS:
            - ../vendor/vendor/include
